# Generated by Django 4.2.1 on 2023-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='blog_summary',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
