# Generated by Django 4.2.1 on 2023-05-19 08:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='blog_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True),
        ),
    ]
