# Generated by Django 4.2.1 on 2023-05-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['updated_date']},
        ),
    ]
