# Generated by Django 4.2.1 on 2023-05-14 01:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='blog_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
