# Generated by Django 4.2.1 on 2023-05-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_topic_blog_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='blog_header_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
